# Generated by Django 3.0.3 on 2020-02-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('has_vehicle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('truck_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=150)),
                ('origin_latitude', models.CharField(max_length=15)),
                ('origin_longitude', models.CharField(max_length=15)),
                ('destiny_name', models.CharField(max_length=150)),
                ('destiny_latitude', models.CharField(max_length=15)),
                ('destiny_longitude', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckpad_driver_register.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckpad_driver_register.Gender'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckpad_driver_register.DriverLicense'),
        ),
        migrations.AddField(
            model_name='driver',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckpad_driver_register.TruckType'),
        ),
    ]
