# Generated by Django 3.0.3 on 2020-02-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckpad_driver_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='has_shipment',
            field=models.BooleanField(default=False),
        ),
    ]
