# Generated by Django 3.0.3 on 2020-02-16 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('truckpad_driver_register', '0002_driver_has_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
