# Generated by Django 3.0.3 on 2020-02-16 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckpad_driver_register', '0003_trucktype_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 14, 25, 56, 2605)),
        ),
    ]
