# Generated by Django 3.0.3 on 2020-02-16 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckpad_driver_register', '0004_trip_trip_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='has_shipment',
            new_name='has_cargo',
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 0, 26, 410656)),
        ),
    ]
