# Generated by Django 3.0.3 on 2020-02-17 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckpad_driver_register', '0005_auto_20200216_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 0, 33, 3, 822653)),
        ),
    ]
